services:
  be:
    container_name: be
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
        JWT_SECRET: ${JWT_SECRET:-"some fucking gibberish"}
        AWS_SES_REGION: ${AWS_SES_REGION}
        AWS_SES_ACCESS_KEY_ID: ${AWS_SES_ACCESS_KEY_ID}
        AWS_SES_SECRET_ACCESS_KEY: ${AWS_SES_SECRET_ACCESS_KEY}
        AWS_SES_FROM_EMAIL: ${AWS_SES_FROM_EMAIL}
        CORS_ORIGINS: ${CORS_ORIGINS}
        CORS_CREDENTIALS: ${CORS_CREDENTIALS}
    env_file:
      - .env
    image: be:dev
    ports:
      - 5000:5000
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - be_database:/var/lib/postgresql/data

volumes:
  be_database:
    driver: local
