services:
  be:
    depends_on:
      db:
        condition: service_healthy
    container_name: be
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
        JWT_SECRET: ${JWT_SECRET:-"some fucking gibberish"}
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DB_HOST=${DB_HOST:-db}
    image: be:dev
    ports:
      - 5000:5000
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - be_database:/var/lib/postgresql

volumes:
  be_database:
    driver: local
