FROM node:20-alpine

ARG NODE_ENV
ARG JWT_SECRET
ARG AWS_SES_REGION
ARG AWS_SES_ACCESS_KEY_ID
ARG AWS_SES_SECRET_ACCESS_KEY
ARG AWS_SES_FROM_EMAIL
ARG CORS_ORIGINS
ARG CORS_CREDENTIALS

ENV NODE_ENV=${NODE_ENV}
ENV JWT_SECRET=${JWT_SECRET}
ENV AWS_SES_REGION=${AWS_SES_REGION}
ENV AWS_SES_ACCESS_KEY_ID=${AWS_SES_ACCESS_KEY_ID}
ENV AWS_SES_SECRET_ACCESS_KEY=${AWS_SES_SECRET_ACCESS_KEY}
ENV AWS_SES_FROM_EMAIL=${AWS_SES_FROM_EMAIL}
ENV CORS_ORIGINS=${CORS_ORIGINS}
ENV CORS_CREDENTIALS=${CORS_CREDENTIALS}

WORKDIR /app

RUN apk update && apk add --no-cache curl

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile --production=false

COPY . .

EXPOSE 5000

CMD ["yarn", "dev"]