services:
  be:
    container_name: be
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
    image: be:dev
    ports:
      - 5000:5000
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - be_database:/var/lib/postgresql/data

volumes:
  be_database:
    driver: local
