services:
  be:
    container_name: be
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
        JWT_SECRET: ${JWT_SECRET:-"some fucking gibberish"}
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DB_HOST=${DB_HOST:-db}
      - PORT=8000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
    ports:
      - 8000:8000
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:17.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - be_database:/var/lib/postgresql/data

volumes:
  be_database:
    driver: local
