export const RoutePrefix = {
  ACTIVITY_LOG: "/activity-log",
  AGENT: "/agent",
  AUTH: "/auth",
  APPRECIATION: "/appreciation",
  COMMENT: "/comment",
  COMMUNICATION: "/communication",
  CONTACT: "/contact",
  DOC: "/doc",
  HEALTH_CHECK: "/health-check",
  LEGACY: "/legacy",
  LOGIN: "/login",
  LOGOUT: "/logout",
  ME: "/me",
  MEMBERSHIP: "/membership",
  OPPORTUNITY: "/opportunity",
  OPPORTUNITY_LINKED: "/opportunity-linked",
  OPPORTUNITY_VOLUNTEER: "/opportunity-volunteer",
  ORGANIZATION: "/organization",
  OPTION: "/option",
  PERSON: "/person",
  POST: "/post",
  REFRESH: "/refresh",
  REQUEST_RESET: "/request-reset",
  RESET_PASSWORD: "/password-reset",
  CHANGE_PASSWORD: "/password-change",
  REGISTER: "/register",
  SWAGGER: "/swagger",
  TRUSTED_DOMAIN: "/trusted-domain",
  USER: "/user",
  VERIFY_EMAIL: "/verify-email",
  VOLUNTEER: "/volunteer",
  VOLUNTEER_LINKED: "/volunteer-linked",
  WORKER: "/worker",
} as const;

// eslint-disable-next-line no-redeclare
export type RoutePrefix = (typeof RoutePrefix)[keyof typeof RoutePrefix];
